name = "real-space-tise"
version = "0.1.0"
author = "Andres Gualdron"
maintainer = "andresmgualdron@gmail.com"

[build]
auto-executables = true
auto-tests = false
link = ["lapack", "blas"]

[install]
library = false
